---
engines:
  env:
  - NODE_ENV=travis
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
path:
  - client/**
  - db/**
  - server/**
  - "**.js"
exclude_paths:
- server/test/**.js
