---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  path:
  - client/**
  - db/**
  - server/**
exclude_paths:
- server/test/
