---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
      NODE_ENV:
      - travis
  eslint:
    enabled: true
ratings:
path:
  - client/**
  - db/**
  - server/**
  - "**.js"
exclude_paths:
- server/test/**.js