export const INVALID_SELECTION = 'INVALID_SELECTION';

export const SELECT_PIECE = 'SELECT_PIECE';

export const UNSELECT_PIECE = 'UNSELECT_PIECE';

export const CAPTURE_PIECE = 'CAPTURE_PIECE';

export const MOVE_PIECE = 'MOVE_PIECE';

export const SET_PLAYER_W = 'SET_PLAYER_W';

export const SET_PLAYER_B = 'SET_PLAYER_B';

export const REQUEST_GAME = 'REQUEST_GAME';

export const RECEIVE_GAME = 'RECEIVE_GAME';

export const GET_REQUEST_FAILURE = 'GET_REQUEST_FAILURE';

export const UPDATE_ROOM_INFO = 'UPDATE_ROOM_INFO';
