export const INVALID_SELECTION = 'INVALID_SELECTION';

export const SELECT_PIECE = 'SELECT_PIECE';

export const CAPTURE_PIECE = 'CAPTURE_PIECE';

export const MOVE_PIECE = 'MOVE_PIECE';

export const REQUEST_GAME = 'REQUEST_GAME';

export const RECEIVE_GAME = 'RECEIVE_GAME';
